export enum IconName {
  Activity = 'activity',
  AlertTriangle = 'alert-triangle',

  Bell = 'bell',
  BookOpen = 'book-open',
  ChevronDown = 'chevron-down',
  ChevronUp = 'chevron-up',
  FeatherUserPlus = 'feather-user-plus',
  User = 'user',
  X = 'x',
  Zap = 'zap',
  Trash = 'trash-2',
  Edit = 'edit-2',
  BAR_CHART = 'bar-chart-2',
  EYE = 'eye',
  EYE_OFF = 'eye-off',
  CLOCK = 'clock',
  PLUS = 'plus',
  ARROW_RIGHT = 'arrow-right',
  ArrowLeft = 'arrow-left',
  MAIL = 'mail',
  PLAY = 'play',
  HOME = 'home',
  CHEVRON_LEFT = 'chevron-left',
  SEARCH = 'search',
  MIC = 'mic',
  DATABASE = 'database',
  MORE_VERTICAL = 'more-vertical',
}
