export enum IconName {
  Activity = 'activity',
  AlertTriangle = 'alert-triangle',
  ArrowLeft = 'arrow-left',
  Bell = 'bell',
  BookOpen = 'book-open',
  ChevronDown = 'chevron-down',
  ChevronUp = 'chevron-up',
  FeatherUserPlus = 'feather-user-plus',
  User = 'user',
  X = 'x',
  Zap = 'zap',
  Trash = 'trash-2',
  Edit = 'edit-2',
  BAR_CHART = 'bar-chart-2',
  EYE = 'eye',
  EYE_OFF = 'eye-off',
  CLOCK = 'clock',
  PLUS = 'plus',
  ARROW_RIGHT = 'arrow-right',
  MAIL = 'mail',
  PLAY = 'play',
}
